# HPC
# BLAS ASSIGNMENT



Use the cell below for all your imports.

In [4]:
import numpy as np
from scipy.linalg.blas import dgemv, ddot, dnrm2
from IPython.display import Image


Create a matrix and a vector using NumPy.Their dtype should be double.

In [7]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.double)
x = np.array([1, 2, 3], dtype=np.double)

Use BLAS functions to perform matrix-vector multiplication

In [8]:
from scipy.linalg import blas
from scipy.linalg import lapack

z = blas.dgemv(alpha =1.0, a = A, x = x)
z

array([14., 32., 50.])

Create two new vectors and calculate their dot product using BLAS functions.

In [9]:
a = np.array([1, 2, 3], dtype=np.double)
b = np.array([4, 5, 6], dtype=np.double)
result = ddot(a, b)
print(result)

32.0


Compute the L2 norm (Euclidean distance) of a vector using BLAS functions

In [10]:
a = np.array([1, 2, 3], dtype=np.double)
norm = dnrm2(a)
print(norm)

3.7416573867739413


Create a 5x5 symmetric matrix and calculate its eigenvalues and eigenvectors using BLAS functions

In [11]:
import numpy as np
from numpy.linalg import eigh

# Create a 5x5 symmetric matrix
A = np.array([[1, 2, 3, 4, 5],
              [2, 6, 7, 8, 9],
              [3, 7, 10, 11, 12],
              [4, 8, 11, 13, 14],
              [5, 9, 12, 14, 15]], dtype=np.double)

w = lapack.dsyev(A)

# Print results
print("Eigenvalues:", w[0])
print("Eigenvectors:",w[1])




Eigenvalues: [-1.06976654  0.17107866  0.66327097  1.12044198 44.11497493]
Eigenvectors: [[ 0.74040618  0.29272354 -0.2622205   0.51923398  0.16657759]
 [ 0.25877317 -0.01176247 -0.5205591  -0.73629348  0.34610435]
 [ 0.20831227  0.32514414  0.75652334 -0.24779322  0.4660024 ]
 [ 0.05805977 -0.80337432  0.07392338  0.23445474  0.53924491]
 [-0.58143804  0.40378901 -0.28716962  0.26813704  0.58695859]]


Given the following matrix A and vector v:

In [12]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.double)
b = np.array([1, 2, 3], dtype=np.double)

Solve the system Ax = b using the LU decomposition method and BLAS functions

In [13]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.double)
b = np.array([1, 2, 3], dtype=np.double)
#lu, piv = lapack.dgetrf(A)
lu = lapack.dgetrf(A)
#x = lapack.dgetri(lu, b)
print(lu)

(array([[7.        , 8.        , 9.        ],
       [0.14285714, 0.85714286, 1.71428571],
       [0.57142857, 0.5       , 0.        ]]), array([2, 2, 2], dtype=int32), 3)
